// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":false,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltMenuScreen2","status":true,"description":"Alternative menu screen layout.","parameters":{"backGroundBitmap":"","maxColsMenu":"4","commandRows":"2","isDisplayStatus":"0"}}
];
